name: Daily PlayStore Rank Scraper

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch: 

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v4 # v3 -> v4로 업데이트 (Node.js 24 지원)

    - name: 파이썬 환경 설정
      uses: actions/setup-python@v5 # v4 -> v5로 업데이트 (Node.js 24 지원)
      with:
        python-version: '3.10'

    - name: 라이브러리 설치
      run: pip install -r requirements.txt

    - name: 파이썬 스크립트 실행
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        SHEET_URL: ${{ secrets.SHEET_URL }}
      run: python scraper.py
